/// Generated by the Protocol Buffers 3.5.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 4.0.0
/// Source file "pose.proto"
/// Syntax "Proto2"

import Foundation
import ProtocolBuffers


public struct PoseRoot {
    public static let `default` = PoseRoot()
    public var extensionRegistry:ExtensionRegistry

    init() {
        extensionRegistry = ExtensionRegistry()
        registerAllExtensions(registry: extensionRegistry)
    }
    public func registerAllExtensions(registry: ExtensionRegistry) {
    }
}

final public class Pose : GeneratedMessage {
    public typealias BuilderType = Pose.Builder

    public static func == (lhs: Pose, rhs: Pose) -> Bool {
        if lhs === rhs {
            return true
        }
        var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
        fieldCheck = fieldCheck && (lhs.hasX == rhs.hasX) && (!lhs.hasX || lhs.x == rhs.x)
        fieldCheck = fieldCheck && (lhs.hasY == rhs.hasY) && (!lhs.hasY || lhs.y == rhs.y)
        fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
        return fieldCheck
    }

    public fileprivate(set) var x:UInt32! = nil
    public fileprivate(set) var hasX:Bool = false

    public fileprivate(set) var y:UInt32! = nil
    public fileprivate(set) var hasY:Bool = false

    required public init() {
        super.init()
    }
    override public func isInitialized() throws {
        if !hasX {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message \(Pose.self): field \"x\" mark required")
        }
        if !hasY {
            throw ProtocolBuffersError.invalidProtocolBuffer("Uninitialized Message \(Pose.self): field \"y\" mark required")
        }
    }
    override public func writeTo(codedOutputStream: CodedOutputStream) throws {
        if hasX {
            try codedOutputStream.writeUInt32(fieldNumber: 1, value:x)
        }
        if hasY {
            try codedOutputStream.writeUInt32(fieldNumber: 2, value:y)
        }
        try unknownFields.writeTo(codedOutputStream: codedOutputStream)
    }
    override public func serializedSize() -> Int32 {
        var serialize_size:Int32 = memoizedSerializedSize
        if serialize_size != -1 {
         return serialize_size
        }

        serialize_size = 0
        if hasX {
            serialize_size += x.computeUInt32Size(fieldNumber: 1)
        }
        if hasY {
            serialize_size += y.computeUInt32Size(fieldNumber: 2)
        }
        serialize_size += unknownFields.serializedSize()
        memoizedSerializedSize = serialize_size
        return serialize_size
    }
    public class func getBuilder() -> Pose.Builder {
        return Pose.classBuilder() as! Pose.Builder
    }
    public func getBuilder() -> Pose.Builder {
        return classBuilder() as! Pose.Builder
    }
    override public class func classBuilder() -> ProtocolBuffersMessageBuilder {
        return Pose.Builder()
    }
    override public func classBuilder() -> ProtocolBuffersMessageBuilder {
        return Pose.Builder()
    }
    public func toBuilder() throws -> Pose.Builder {
        return try Pose.builderWithPrototype(prototype:self)
    }
    public class func builderWithPrototype(prototype:Pose) throws -> Pose.Builder {
        return try Pose.Builder().mergeFrom(other:prototype)
    }
    override public func encode() throws -> Dictionary<String,Any> {
        try isInitialized()
        var jsonMap:Dictionary<String,Any> = Dictionary<String,Any>()
        if hasX {
            jsonMap["x"] = UInt(x)
        }
        if hasY {
            jsonMap["y"] = UInt(y)
        }
        return jsonMap
    }
    override class public func decode(jsonMap:Dictionary<String,Any>) throws -> Pose {
        return try Pose.Builder.decodeToBuilder(jsonMap:jsonMap).build()
    }
    override class public func fromJSON(data:Data) throws -> Pose {
        return try Pose.Builder.fromJSONToBuilder(data:data).build()
    }
    override public func getDescription(indent:String) throws -> String {
        var output = ""
        if hasX {
            output += "\(indent) x: \(x) \n"
        }
        if hasY {
            output += "\(indent) y: \(y) \n"
        }
        output += unknownFields.getDescription(indent: indent)
        return output
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasX {
                hashCode = (hashCode &* 31) &+ x.hashValue
            }
            if hasY {
                hashCode = (hashCode &* 31) &+ y.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Pose"
    }
    override public func className() -> String {
        return "Pose"
    }
    //Meta information declaration end

    final public class Builder : GeneratedMessageBuilder {
        fileprivate var builderResult:Pose = Pose()
        public func getMessage() -> Pose {
            return builderResult
        }

        required override public init () {
            super.init()
        }
        public var x:UInt32 {
            get {
                return builderResult.x
            }
            set (value) {
                builderResult.hasX = true
                builderResult.x = value
            }
        }
        public var hasX:Bool {
            get {
                return builderResult.hasX
            }
        }
        @discardableResult
        public func setX(_ value:UInt32) -> Pose.Builder {
            self.x = value
            return self
        }
        @discardableResult
        public func clearX() -> Pose.Builder{
            builderResult.hasX = false
            builderResult.x = nil
            return self
        }
        public var y:UInt32 {
            get {
                return builderResult.y
            }
            set (value) {
                builderResult.hasY = true
                builderResult.y = value
            }
        }
        public var hasY:Bool {
            get {
                return builderResult.hasY
            }
        }
        @discardableResult
        public func setY(_ value:UInt32) -> Pose.Builder {
            self.y = value
            return self
        }
        @discardableResult
        public func clearY() -> Pose.Builder{
            builderResult.hasY = false
            builderResult.y = nil
            return self
        }
        override public var internalGetResult:GeneratedMessage {
            get {
                return builderResult
            }
        }
        @discardableResult
        override public func clear() -> Pose.Builder {
            builderResult = Pose()
            return self
        }
        override public func clone() throws -> Pose.Builder {
            return try Pose.builderWithPrototype(prototype:builderResult)
        }
        override public func build() throws -> Pose {
            try checkInitialized()
            return buildPartial()
        }
        public func buildPartial() -> Pose {
            let returnMe:Pose = builderResult
            return returnMe
        }
        @discardableResult
        public func mergeFrom(other:Pose) throws -> Pose.Builder {
            if other == Pose() {
                return self
            }
            if other.hasX {
                x = other.x
            }
            if other.hasY {
                y = other.y
            }
            try merge(unknownField: other.unknownFields)
            return self
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream) throws -> Pose.Builder {
            return try mergeFrom(codedInputStream: codedInputStream, extensionRegistry:ExtensionRegistry())
        }
        @discardableResult
        override public func mergeFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pose.Builder {
            let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(copyFrom:self.unknownFields)
            while (true) {
                let protobufTag = try codedInputStream.readTag()
                switch protobufTag {
                case 0: 
                    self.unknownFields = try unknownFieldsBuilder.build()
                    return self

                case 8:
                    x = try codedInputStream.readUInt32()

                case 16:
                    y = try codedInputStream.readUInt32()

                default:
                    if (!(try parse(codedInputStream:codedInputStream, unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:protobufTag))) {
                        unknownFields = try unknownFieldsBuilder.build()
                        return self
                    }
                }
            }
        }
        class override public func decodeToBuilder(jsonMap:Dictionary<String,Any>) throws -> Pose.Builder {
            let resultDecodedBuilder = Pose.Builder()
            if let jsonValueX = jsonMap["x"] as? UInt {
                resultDecodedBuilder.x = UInt32(jsonValueX)
            } else if let jsonValueX = jsonMap["x"] as? String {
                resultDecodedBuilder.x = UInt32(jsonValueX)!
            }
            if let jsonValueY = jsonMap["y"] as? UInt {
                resultDecodedBuilder.y = UInt32(jsonValueY)
            } else if let jsonValueY = jsonMap["y"] as? String {
                resultDecodedBuilder.y = UInt32(jsonValueY)!
            }
            return resultDecodedBuilder
        }
        override class public func fromJSONToBuilder(data:Data) throws -> Pose.Builder {
            let jsonData = try JSONSerialization.jsonObject(with:data, options: JSONSerialization.ReadingOptions(rawValue: 0))
            guard let jsDataCast = jsonData as? Dictionary<String,Any> else {
              throw ProtocolBuffersError.invalidProtocolBuffer("Invalid JSON data")
            }
            return try Pose.Builder.decodeToBuilder(jsonMap:jsDataCast)
        }
    }

}

extension Pose: GeneratedMessageProtocol {
    public class func parseArrayDelimitedFrom(inputStream: InputStream) throws -> Array<Pose> {
        var mergedArray = Array<Pose>()
        while let value = try parseDelimitedFrom(inputStream: inputStream) {
          mergedArray.append(value)
        }
        return mergedArray
    }
    public class func parseDelimitedFrom(inputStream: InputStream) throws -> Pose? {
        return try Pose.Builder().mergeDelimitedFrom(inputStream: inputStream)?.build()
    }
    public class func parseFrom(data: Data) throws -> Pose {
        return try Pose.Builder().mergeFrom(data: data, extensionRegistry:PoseRoot.default.extensionRegistry).build()
    }
    public class func parseFrom(data: Data, extensionRegistry:ExtensionRegistry) throws -> Pose {
        return try Pose.Builder().mergeFrom(data: data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(inputStream: InputStream) throws -> Pose {
        return try Pose.Builder().mergeFrom(inputStream: inputStream).build()
    }
    public class func parseFrom(inputStream: InputStream, extensionRegistry:ExtensionRegistry) throws -> Pose {
        return try Pose.Builder().mergeFrom(inputStream: inputStream, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream) throws -> Pose {
        return try Pose.Builder().mergeFrom(codedInputStream: codedInputStream).build()
    }
    public class func parseFrom(codedInputStream: CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Pose {
        return try Pose.Builder().mergeFrom(codedInputStream: codedInputStream, extensionRegistry:extensionRegistry).build()
    }
    public subscript(key: String) -> Any? {
        switch key {
        case "x": return self.x
        case "y": return self.y
        default: return nil
        }
    }
}
extension Pose.Builder: GeneratedMessageBuilderProtocol {
    public typealias GeneratedMessageType = Pose
    public subscript(key: String) -> Any? {
        get { 
            switch key {
            case "x": return self.x
            case "y": return self.y
            default: return nil
            }
        }
        set (newSubscriptValue) { 
            switch key {
            case "x":
                guard let newSubscriptValue = newSubscriptValue as? UInt32 else {
                    return
                }
                self.x = newSubscriptValue
            case "y":
                guard let newSubscriptValue = newSubscriptValue as? UInt32 else {
                    return
                }
                self.y = newSubscriptValue
            default: return
            }
        }
    }
}

// @@protoc_insertion_point(global_scope)
